package com.example.abc.myapplication47.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.abc.myapplication47.Collection;
import com.example.abc.myapplication47.User;

import com.example.abc.myapplication47.greendao.CollectionDao;
import com.example.abc.myapplication47.greendao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CollectionDao collectionDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        collectionDao = new CollectionDao(collectionDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Collection.class, collectionDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        collectionDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
